// <auto-generated />
namespace meetometer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IdentityDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentityDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201409231615580_IdentityDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
